title = "MSNE Blog"
baseurl = "https://msne2016.github.io"
languageCode = "en-us"

author = "MSNE Students"
copyright = "MSNE All rights reserved."

[params]
  logo      = "/img/neuroengineering-ensemble.jpg"
  github    = "https://github.com/MSNE2016"
